// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTymeq9cgD8Qu0kpNaasqTqZUVOOW3qc',
    appId: '1:744327101985:web:579fa1578d38664f8b6d60',
    messagingSenderId: '744327101985',
    projectId: 'chat-application-b09eb',
    authDomain: 'chat-application-b09eb.firebaseapp.com',
    storageBucket: 'chat-application-b09eb.appspot.com',
    measurementId: 'G-M6DGWWYS32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf94k1msnNI8NT0VLyx8Isaw_pf9eCU8k',
    appId: '1:744327101985:android:e75d68878a4142b18b6d60',
    messagingSenderId: '744327101985',
    projectId: 'chat-application-b09eb',
    storageBucket: 'chat-application-b09eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7Rp0RbhGn__AlTr7C_baCNQXJia-7JY0',
    appId: '1:744327101985:ios:1d1ee27d687c83d58b6d60',
    messagingSenderId: '744327101985',
    projectId: 'chat-application-b09eb',
    storageBucket: 'chat-application-b09eb.appspot.com',
    iosClientId: '744327101985-b3098ccigsou12ani316f8kn17sl9ol5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7Rp0RbhGn__AlTr7C_baCNQXJia-7JY0',
    appId: '1:744327101985:ios:1d1ee27d687c83d58b6d60',
    messagingSenderId: '744327101985',
    projectId: 'chat-application-b09eb',
    storageBucket: 'chat-application-b09eb.appspot.com',
    iosClientId: '744327101985-b3098ccigsou12ani316f8kn17sl9ol5.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappWithFirebase',
  );
}
